[package]
name = "blsful"
version = "1.0.0"
authors = ["Michael Lodder <redmike7@gmail.com>"]
edition = "2021"
license = "Apache-2.0 or MIT"
homepage = "https://github.com/mikelodder7/blsful"
repository = "https://github.com/mikelodder7/blsful"
readme = "README.md"
categories = [
    "cryptography",
    "asynchronous",
    "authentication",
    "no-std",
    "algorithms",
]
keywords = ["crypto", "signature", "signing", "bls"]
description = """BLS signature implementation according to the IETF spec on the BLS12-381 curve."""

[features]
default = ["std"]
alloc = []
std = ["alloc", "iso8601-timestamp"]

[dependencies]
bls12_381_plus = "0.5.5"
ff = { version = "0.12", default-features = false }
group = "0.12"
hex = { version = "0.4", default-features = false }
hkdf = { version = "0.11", default-features = false }
iso8601-timestamp = { version = "0.2.10", optional = true }
pairing = "0.22"
rand_core = "0.6"
serde = { version = "1.0", default-features = false, features = ["derive"] }
sha2 = { version = "0.9", default-features = false }
subtle = { version = "2.4", default-features = false }
vsss-rs = { version = "2.7.0", default-features = false, features = ["elliptic-curve"] }
zeroize = { version = "1.5", features = ["zeroize_derive"] }

[dev-dependencies]
rand_xorshift = "0.3"
serde_bare = "0.5"
serde_json = "1.0"
